"""Render one page that shows every guarded repository's claims at a glance.

The gates live in 22 repositories, so the honest answer to "are your numbers checked?" is spread
across 22 CI runs nobody will open. This reads each repository's claims file and prints a single
table: how many claims, how many are machine-checked, how many are still manual, and when the file
was last updated.

It is generated, never hand-edited: the row for a repository comes from that repository's own
`claims.json`, fetched at a pinned ref. A page that people maintain by hand drifts from the files
it claims to summarise, which is the exact failure this project exists to catch.

Two deliberate limits:
  - the numbers here can be stale between regenerations; each row carries the `updated` date the
    claims file itself declares, and the header carries the generation date;
  - a sibling repository's file can be unreachable. That is reported as a `?` row rather than
    silently dropped, because a missing row would make the portfolio look smaller than it is.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

GENERATED_NOTE = (
    "Generated by `verify-claims index` from each repository's own claims file — "
    "do not edit by hand."
)


@dataclass
class Row:
    repo: str          # short name, shown in the table
    slug: str          # owner/name, used for the link
    total: int | None
    machine: int | None
    manual: int | None
    updated: str
    error: str = ""


def read_claims(source: str, fetch=None) -> dict:
    """Read one claims document from a local path or a URL."""
    if source.startswith(("http://", "https://")):
        if fetch is None:
            raise ValueError("fetch callable required for URLs")
        return json.loads(fetch(source))
    return json.loads(Path(source).read_text(encoding="utf-8"))


def row_for(repo: str, doc: dict) -> Row:
    claims = doc.get("claims") or []
    manual = sum(1 for c in claims if "manual" in (c.get("check") or {}))
    return Row(
        repo=repo.split("/")[-1],
        slug=repo,
        total=len(claims),
        machine=len(claims) - manual,
        manual=manual,
        updated=str(doc.get("updated") or "-"),
    )


def render(rows: Iterable[Row], generated: str, source_note: str) -> str:
    rows = list(rows)
    total = sum(r.total or 0 for r in rows)
    machine = sum(r.machine or 0 for r in rows)
    manual = sum(r.manual or 0 for r in rows)
    reachable = [r for r in rows if r.total is not None]
    lines = [
        "# Every published number, and who checks it",
        "",
        GENERATED_NOTE,
        "",
        f"Generated {generated} · {source_note}",
        "",
        f"**{total} claims across {len(reachable)} repositories — {machine} machine-checked, "
        f"{manual} still manual.** A manual claim is one nobody can recompute from the repository; "
        "each carries a written reason instead of a command.",
        "",
        "| repository | claims | machine | manual | claims file updated |",
        "| --- | ---: | ---: | ---: | --- |",
    ]
    for r in sorted(rows, key=lambda r: (r.total is None, -(r.total or 0), r.repo)):
        if r.total is None:
            lines.append(f"| `{r.repo}` | ? | ? | ? | unreachable: {r.error} |")
        else:
            lines.append(f"| [`{r.repo}`](https://github.com/{r.slug}) | {r.total} | "
                         f"{r.machine} | {r.manual} | {r.updated} |")
    lines += [
        "",
        f"**Total** · {total} claims · {machine} machine-checked · {manual} manual",
        "",
        "## How to read this",
        "",
        "- **machine** means a command in that repository recomputes the number from committed "
        "data, and CI fails when it stops reproducing.",
        "- **manual** means the number is published but not recomputable (an upstream quote, a "
        "screenshot, a model-side statistic). Those are the honest gaps: the claims file names, per "
        "row, what artifact would be needed to check it.",
        "- This counts the claims that exist today. `docs/measurement.md` counts what an audit "
        "examined at the time (553 claims, 131 defective) — different denominators, both labelled.",
        "- A repository with a high manual count is not necessarily worse than one with none — it "
        "may simply publish more numbers that depend on the outside world. The count says how much "
        "is checkable today, not how careful the authors were.",
        "",
    ]
    return "\n".join(lines)


def summarise(text: str) -> tuple[int, int, int, int]:
    """(rows, claims, machine, manual) read back out of a rendered page.

    Used by the repository's own claim: the summary line must agree with the table under it.
    """
    rows = machine = manual = 0
    for line in text.splitlines():
        if line.startswith("| [`"):
            rows += 1
            cells = [c.strip() for c in line.strip("|").split("|")]
            machine += int(cells[2])
            manual += int(cells[3])
    for line in text.splitlines():
        if line.startswith(f"**Total** · "):
            total = int(line.split("·")[1].strip().split()[0])
            return rows, total, machine, manual
    raise ValueError("no total line in the rendered page")
